Modul2TestMiljanVasovic/Controllers/ArtikalController.cs
using FluentValidation;
using FluentValidation.Results;
using Modul2TestMiljanVasovic.Models;
using Modul2TestMiljanVasovic.Models.Repository;
using Modul2TestMiljanVasovic.Models.ViewModels;
using Modul2TestMiljanVasovic.Validators;
using System;
using PagedList.Mvc;
using PagedList;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Modul2TestMiljanVasovic.Controllers
{
    public class ArtikalController : Controller
    {

        // GET: Artikal
        private IrepositoryArtikal artikalRepo = new ArtikalRepo();

        BindingList<string> errors = new BindingList<string>();

        ArtikalKategorijaViewModel artikalKategorijaViewModel = new ArtikalKategorijaViewModel();
        
      

        // GET: Auto
        public ActionResult Index(string searchString,int? page)
        {

            int pageSize = 7;
            
            int pageNumber = (page ?? 1);
           
            
            
                if (!String.IsNullOrEmpty(searchString))
                {
                    var artikli = artikalRepo.GetAll();
                    artikli = artikli.Where(s => s.NazivArtikla.Contains(searchString) ||
                    s.Opis.Contains(searchString) ||
                    s.Marka.Contains(searchString));

               
                    return View(artikli.ToPagedList(pageNumber, pageSize));
                }
            
           

                
                
            return View(artikalRepo.GetAll().ToPagedList(pageNumber, pageSize));


            
        }

        public ActionResult Detalji(int id)
        {
            var artikal = artikalRepo.GetById(id);

            return View(artikal);
        }
       

        //Get
        public ActionResult Create()
        {


            return View();
        }
        [HttpPost]
        public ActionResult Create(ArtikalKategorijaViewModel artikalKategorijaViewModel)
        {

            
                ArtikalModel artikalModel1 = new ArtikalModel() {
                    NazivArtikla = artikalKategorijaViewModel.ArtikalModel.NazivArtikla,
                    Cena = artikalKategorijaViewModel.ArtikalModel.Cena,
                    Marka = artikalKategorijaViewModel.ArtikalModel.Marka,
                    Opis = artikalKategorijaViewModel.ArtikalModel.Opis,
                    IdKategorije = artikalKategorijaViewModel.SelektovaniKategorejeOdeceId,
                    IdTipa = artikalKategorijaViewModel.SelektovaniTipOdeceId };

                ArtikalRepo artikalRepo = new ArtikalRepo();




            


            //}
            //Validacija
            Validator validator = new Validator();
            FluentValidation.Results.ValidationResult results = validator.Validate(artikalModel1);

            if (results.IsValid==false)
            {
                foreach (ValidationFailure failure in results.Errors)
                {
                    errors.Add($"{failure.PropertyName}:{failure.ErrorMessage}");
                    
                }
            }
            //       
            if (artikalRepo.Create(artikalModel1)==false)
            {

                return View(artikalKategorijaViewModel);
            }

            return RedirectToAction("Index");



        }








        public ActionResult Brisi(int id)
        {
            artikalRepo.Delete(id);

            return RedirectToAction("Index");
        }

        // [HttpGet]

        public ActionResult Izmeni(int id)
        {
            ArtikalRepo artikalRepo = new ArtikalRepo();
            ArtikalModel data = artikalRepo.GetById(id);

            ArtikalModel artikalModel1 = new ArtikalModel() { Id = data.Id,NazivArtikla=data.NazivArtikla,Cena=data.Cena,Marka=data.Marka,Opis=data.Opis,IdKategorije=data.IdKategorije,IdTipa=data.IdTipa };



            ArtikalKategorijaViewModel artikalKategorijaViewModel = new ArtikalKategorijaViewModel() { SelektovaniKategorejeOdeceId=data.IdKategorije, ArtikalModel=artikalModel1 };


            return View(artikalKategorijaViewModel);
        }
        [HttpPost]
        public ActionResult Izmeni(ArtikalKategorijaViewModel model)
        {

            ArtikalModel artikalModel = new ArtikalModel() { Id = model.ArtikalModel.Id,NazivArtikla=model.ArtikalModel.NazivArtikla,Cena=model.ArtikalModel.Cena,Marka=model.ArtikalModel.Marka,Opis=model.ArtikalModel.Opis,IdKategorije=model.SelektovaniKategorejeOdeceId,IdTipa=model.SelektovaniTipOdeceId};

            ArtikalRepo artikalRepo = new ArtikalRepo();
            artikalRepo.Update(artikalModel);

            return RedirectToAction("Index");
        }
    }
}

Modul2TestMiljanVasovic/Views/Artikal/Create.cshtml
@model Modul2TestMiljanVasovic.Models.ViewModels.ArtikalKategorijaViewModel
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<head>
    <script src="~/Scripts/Skripta1.js"></script>
</head>

<a href="/Artikal/Index">Listing artikala</a>

<h2>Dodaj novi artikal</h2>
@using (Html.BeginForm("Create", "Artikal", FormMethod.Post))
{
    <form method="post">
        <div class="form-group">
            @Html.HiddenFor(n => n.ArtikalModel.Id)


        </div>
        <div class="form-group">
            @Html.LabelFor(n => n.ArtikalModel.NazivArtikla)
            @Html.TextBoxFor(n => n.ArtikalModel.NazivArtikla)
            @Html.ValidationMessageFor(n => n.ArtikalModel.NazivArtikla)
        </div>
        <div class="form-group">
            @Html.LabelFor(n => n.ArtikalModel.Cena)
            @Html.TextBoxFor(n => n.ArtikalModel.Cena)
            @Html.ValidationMessageFor(n => n.ArtikalModel.Cena)
        </div>
        <div class="form-group">
            @Html.LabelFor(n => n.ArtikalModel.Marka)
            @Html.TextBoxFor(n => n.ArtikalModel.Marka)
            @Html.ValidationMessageFor(n => n.ArtikalModel.Marka)
        </div>
        <div class="form-group">
            @Html.LabelFor(n => n.ArtikalModel.Opis)
            @Html.TextBoxFor(n => n.ArtikalModel.Opis)
            @Html.ValidationMessageFor(n => n.ArtikalModel.Opis)
        </div>


        <div class="form-group">
            <div class="col-md-10">
                <b>Izaberite kategoriju:</b>
                @Html.DropDownListFor(m => m.SelektovaniKategorejeOdeceId, new SelectList(Modul2TestMiljanVasovic.fonts.Helper.List.GetAll(), "KategorijaId", "NazivKategorije"))


            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <br />
                <b>Izaberite tip:</b>
                @Html.DropDownListFor(m => m.SelektovaniTipOdeceId, new SelectList(Modul2TestMiljanVasovic.fonts.Helper.List1.GetAll(), "TipId", "NazivTipa"))

                <br />
                <br />
                <input type="submit" value="Submit" />
            </div>
        </div>

        @*@section scripts
            {
                @Scripts.Render("~/bundles/Validation.js")
                }*@

    </form>

}

Modul2TestMiljanVasovic/Views/Artikal/Index.cshtml
@model IPagedList<Modul2TestMiljanVasovic.Models.ArtikalModel>


@{
    ViewBag.Title = "Index";
}
@using PagedList.Mvc;
@using PagedList;
<h2>Index</h2>



<h2>Listing svih artikala</h2>


<p>
    <a href="/Artikal/Create">Dodaj novi artikal</a>
</p>
<p>
    <a href="/Artikal/Index">Pocetna stranica</a>
</p>
<p>
    <a href="/KategorijaOdece/Index">Listing kategorija odece</a>

</p>
<p>
    <a href="/TipOdece/Index">Listing Tipova odece</a>
</p>

@using (Html.BeginForm())
{
    <p>
        Find by name: @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
    </p>
}


<table class="table">
    <tr>
        <th>
            Id
        </th>
        <th>
            Naziv
        </th>

        <th>
            Cena
        </th>
        <th>
            Marka
        </th>
        <th>
            Opis
        </th>
        <th>
            Identifikacioni broj kategorije
        </th>

        <th>
            Identifikacioni broj tipa odece
        </th>

    </tr>

        @foreach (var item in Model)
        {
        <tr>
            <td>
                @item.Id
            </td>
            <td>
                @item.NazivArtikla
            </td>
            <td>
                @item.Cena
            </td>
            <td>
                @item.Marka
            </td>
            <td>
                @item.Opis
            </td>
            <td>
                @item.IdKategorije
            </td>


            <td>
                @item.IdTipa
            </td>

           



            <td>
                <a href="/Artikal/Brisi/@item.Id">Brisi</a>
            </td>
            <td>
                <a href="/Artikal/Izmeni/@item.Id">Izmeni</a>
            </td>

        </tr>

        }

</table>
@Html.PagedListPager(Model, page => Url.Action("Index", "Artikal", new { page, searchString = Request.QueryString["searchString"] }))

Modul2TestMiljanVasovic/Views/Artikal/Izmeni.cshtml
@model Modul2TestMiljanVasovic.Models.ViewModels.ArtikalKategorijaViewModel
@{
    ViewBag.Title = "Izmeni";
}

<h2>Izmeni</h2>






@using (Html.BeginForm("Izmeni", "Artikal", FormMethod.Post))
{
    <form method="post">
        <div class="form-group">
            @Html.HiddenFor(n => n.ArtikalModel.Id)

        </div>
        <div class="form-group">
            @Html.LabelFor(n => n.ArtikalModel.NazivArtikla)
            @Html.TextBoxFor(n => n.ArtikalModel.NazivArtikla)
            @Html.ValidationMessageFor(n => n.ArtikalModel.NazivArtikla)
        </div>
        <div class="form-group">
            @Html.LabelFor(n => n.ArtikalModel.Cena)
            @Html.TextBoxFor(n => n.ArtikalModel.Cena)
            @Html.ValidationMessageFor(n => n.ArtikalModel.Cena)
        </div>
        <div class="form-group">
            @Html.LabelFor(n => n.ArtikalModel.Marka)
            @Html.TextBoxFor(n => n.ArtikalModel.Marka)
            @Html.ValidationMessageFor(n => n.ArtikalModel.Marka)
        </div>
        <div class="form-group">
            @Html.LabelFor(n => n.ArtikalModel.Opis)
            @Html.TextBoxFor(n => n.ArtikalModel.Opis)
            @Html.ValidationMessageFor(n => n.ArtikalModel.Opis)
        </div>


        <div class="form-group">
            <div class="col-md-10">
                <br />
                <b>Izaberite kategoriju odece</b>
                @Html.DropDownListFor(m => m.SelektovaniKategorejeOdeceId, new SelectList(Modul2TestMiljanVasovic.fonts.Helper.List.GetAll(), "KategorijaId", "NazivKategorije"))
                @Html.ValidationMessageFor(m => m.SelektovaniKategorejeOdeceId)

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <br />
                <b>Izaberite tip odece</b>
                @Html.DropDownListFor(m => m.SelektovaniTipOdeceId, new SelectList(Modul2TestMiljanVasovic.fonts.Helper.List1.GetAll(), "TipId", "NazivTipa"))
                @Html.ValidationMessageFor(m => m.SelektovaniTipOdeceId)
                <br />
                <br/>
                <input type="submit" value="Submit" />
            </div>
        </div>
        @*@section scripts
            {
                @Scripts.Render("~/bundles/Validation.js")
                }*@

    </form>

}