Modul2TestMiljanVasovic/Controllers/TipOdeceController.cs
using FluentValidation.Results;
using Modul2TestMiljanVasovic.Models;
using Modul2TestMiljanVasovic.Models.Repository;
using Modul2TestMiljanVasovic.Models.ViewModels;
using Modul2TestMiljanVasovic.Validators;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Modul2TestMiljanVasovic.Controllers
{
    public class TipOdeceController : Controller
    {
        // GET: TipOdece

        private ITipOdece tipRepo = new TipRepo();
         BindingList<string> errors = new BindingList<string>();


        // GET: TipMotora

        public ActionResult Index()
        {
            var tipoviOdece = tipRepo.GetAll();

            return View(tipoviOdece);
        }
        //Get
        public ActionResult Details(int id)
        {
            var tip1 = tipRepo.GetById(id);

            return View(tip1);
        }
        //get
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductCategory/Create
        [HttpPost]
        public ActionResult Create(ArtikalKategorijaViewModel model)
        {

            TipOdeceModel tipOdece1 = new TipOdeceModel() {TipId=model.tipOdeceModel.TipId,NazivTipa=model.tipOdeceModel.NazivTipa };
            TipRepo tipRepo = new TipRepo();

            //Validacija
            Validator2 validator2 = new Validator2();
            FluentValidation.Results.ValidationResult results = validator2.Validate(tipOdece1);

            if (results.IsValid == false)
            {
                foreach (ValidationFailure failure in results.Errors)
                {
                    errors.Add($"{failure.PropertyName}:{failure.ErrorMessage}");

                }
            }
            if (tipRepo.Create(tipOdece1) == false)
            {

                return View(model);
            }
            return RedirectToAction("Index");
        }




        public ActionResult Brisi(int id)
        {
            tipRepo.Delete(id);
            return RedirectToAction("Index");
        }

        // [HttpGet]
        public ActionResult Izmeni(int id)
        {

            TipRepo tipRepo = new TipRepo();
            var data = tipRepo.GetById(id);

            TipOdeceModel tipOdeceModel1 = new TipOdeceModel() {TipId=data.TipId,NazivTipa=data.NazivTipa };
            ArtikalKategorijaViewModel artikalKategorijaViewModel = new ArtikalKategorijaViewModel() { tipOdeceModel=tipOdeceModel1, SelektovaniTipOdeceId=data.TipId };

            return View(artikalKategorijaViewModel);
        }
        [HttpPost]
        public ActionResult Izmeni(ArtikalKategorijaViewModel artikalKategorijaViewModel)
        {
            TipOdeceModel tipOdeceModel = new TipOdeceModel() { TipId=artikalKategorijaViewModel.tipOdeceModel.TipId,NazivTipa=artikalKategorijaViewModel.tipOdeceModel.NazivTipa };

            TipRepo tipRepo = new TipRepo();
            tipRepo.Update(tipOdeceModel);

            return RedirectToAction("Index");

        }
    }




}

Modul2TestMiljanVasovic/Views/TipOdece/Create.cshtml
@model Modul2TestMiljanVasovic.Models.ViewModels.ArtikalKategorijaViewModel
@{
    ViewBag.Title = "Create";
}

<a href="/TipOdece/Index">Listing tipova odece</a>

<h2>Dodaj tip odece</h2>

@using (Html.BeginForm("Create", "TipOdece", FormMethod.Post))
{
    <form method="post">
        <div class="form-group">
            @Html.HiddenFor(m => m.tipOdeceModel.TipId)

        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.tipOdeceModel.NazivTipa)
            @Html.TextBoxFor(m => m.tipOdeceModel.NazivTipa)
            @Html.ValidationMessageFor(m => m.tipOdeceModel.TipId)
        </div>
        <div class="form-group">
            <input class="btn-default" type="submit" />
        </div>
    </form>
}

Modul2TestMiljanVasovic/Views/TipOdece/Index.cshtml
@model IEnumerable<Modul2TestMiljanVasovic.Models.TipOdeceModel>
@{
    ViewBag.Title = "Index";
}


    <h2>Listing svih tipova odece</h2>

    <p>
        <a href="/TipOdece/Create">Dodaj novi tip</a>
    </p>
    <p>
        <a href="/Artikal/Index">Listing artikala</a>
    </p>
    <table class="table">
        <tr>
            <th>
                Identifikacioni broj tipa odece
            </th>
            <th>
                Naziv tipa odece
            </th>
            <th>
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.TipId
                </td>
                <td>
                    @item.NazivTipa
                </td>
                <td>
                    <a href="/TipOdece/Brisi/@item.TipId ">Brisi</a>
                </td>
                <td>
                    <a href="/TipOdece/Izmeni/@item.TipId">Izmeni</a>
                </td>
            </tr>
        }

    </table>

Modul2TestMiljanVasovic/Views/TipOdece/Izmeni.cshtml
@model Modul2TestMiljanVasovic.Models.ViewModels.ArtikalKategorijaViewModel
@{
    ViewBag.Title = "Izmeni";
}




<h2>Izmeni tip odece</h2>

@using (Html.BeginForm("Izmeni", "TipOdece", FormMethod.Post))
{
    <form method="post">
        <div class="form-group">
            @Html.HiddenFor(m => m.tipOdeceModel.TipId)

        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.tipOdeceModel.NazivTipa)
            @Html.TextBoxFor(m => m.tipOdeceModel.NazivTipa)
            @Html.ValidationMessageFor(m => m.tipOdeceModel.TipId)
        </div>
        <div class="form-group">
            <input class="btn-default" type="submit" />
        </div>
    </form>
}