Modul2TestMiljanVasovic/Controllers/KategorijaOdeceController.cs
using FluentValidation.Results;
using Modul2TestMiljanVasovic.Models;
using Modul2TestMiljanVasovic.Models.Repository;
using Modul2TestMiljanVasovic.Models.ViewModels;
using Modul2TestMiljanVasovic.Validators;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Modul2TestMiljanVasovic.Controllers
{
    public class KategorijaOdeceController: Controller
    {
        
        private IrepositoryKategorijaOdece kategorijaRepo =new KategorijaRepo();

        BindingList<string> errors = new BindingList<string>();

        KategorijaOdeceModel KategorijaOdeceModel = new KategorijaOdeceModel();

        // GET: TipMotora

        public ActionResult Index()
        {
            var kategorije = kategorijaRepo.GetAll();

            return View(kategorije);
        }
        //Get
        public ActionResult Details(int id)
        {
            var kategorijeOdece = kategorijaRepo.GetById(id);

            return View(kategorijeOdece);
        }
        //get
        public ActionResult Create()
        {
            return View();
        }

       
        [HttpPost]
        public ActionResult Create(ArtikalKategorijaViewModel artikalKategorijaViewModel)
        {
            
            KategorijaOdeceModel KategorijaOdeceModel = new KategorijaOdeceModel() { KategorijaId=artikalKategorijaViewModel.KategorijaOdeceModel.KategorijaId,NazivKategorije=artikalKategorijaViewModel.KategorijaOdeceModel.NazivKategorije};
            KategorijaRepo kategorijaRepo = new KategorijaRepo();
           

            //Validacija
            Validator1 validator1 = new Validator1();
            FluentValidation.Results.ValidationResult results = validator1.Validate(KategorijaOdeceModel);

            if (results.IsValid == false)
            {
                foreach (ValidationFailure failure in results.Errors)
                {
                    errors.Add($"{failure.PropertyName}:{failure.ErrorMessage}");

                }
            }
            if (kategorijaRepo.Create(KategorijaOdeceModel) == false)
            {

                return View(artikalKategorijaViewModel);
            }

            return RedirectToAction("Index");   // nakon uspesnog dodavanja daj listing svih proizvoda
           
            
        }




        public ActionResult Brisi(int id)
        {
            kategorijaRepo.Delete(id);
            return RedirectToAction("Index");
        }

        // [HttpGet]
        public ActionResult Izmeni(int id)
        {

            KategorijaRepo kategorijaRepo = new KategorijaRepo();
            var data = kategorijaRepo.GetById(id);

            KategorijaOdeceModel kategorijaOdeceModel1 = new KategorijaOdeceModel() {KategorijaId=data.KategorijaId,NazivKategorije=data.NazivKategorije };
            ArtikalKategorijaViewModel artikalKategorijaViewModel = new ArtikalKategorijaViewModel() {  KategorijaOdeceModel=kategorijaOdeceModel1 ,SelektovaniKategorejeOdeceId=data.KategorijaId };

            return View(artikalKategorijaViewModel);
        }
        [HttpPost]
        public ActionResult Izmeni(ArtikalKategorijaViewModel model)
        {
            KategorijaOdeceModel kategorijaOdeceModel = new KategorijaOdeceModel() {KategorijaId=model.KategorijaOdeceModel.KategorijaId,NazivKategorije=model.KategorijaOdeceModel.NazivKategorije};

            KategorijaRepo kategorijaRepo = new KategorijaRepo();
            kategorijaRepo.Update(kategorijaOdeceModel);

            return RedirectToAction("Index");

        }
    }
}

Modul2TestMiljanVasovic/Views/KategorijaOdece/Create.cshtml
@model Modul2TestMiljanVasovic.Models.ViewModels.ArtikalKategorijaViewModel
@{
    ViewBag.Title = "Create";
}


<a href="/KategorijaOdece/Index">Listing kategorija odece</a>

<h2>Dodaj kategoriju odece</h2>

@using (Html.BeginForm("Create", "KategorijaOdece", FormMethod.Post))
{
    <form method="post">
        <div class="form-group">
            @Html.HiddenFor(m => m.KategorijaOdeceModel.KategorijaId)

        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.KategorijaOdeceModel.NazivKategorije)
            @Html.TextBoxFor(m => m.KategorijaOdeceModel.NazivKategorije)
            @Html.ValidationMessageFor(m => m.KategorijaOdeceModel.NazivKategorije)
        </div>
        <div class="form-group">
            <input class="btn-default" type="submit" />
        </div>
    </form>
}

Modul2TestMiljanVasovic/Views/KategorijaOdece/Index.cshtml
@model IEnumerable<Modul2TestMiljanVasovic.Models.KategorijaOdeceModel>
@{
    ViewBag.Title = "Index";
}


    <h2>Listing svih kategorija</h2>

    <p>
        <a href="/KategorijaOdece/Create">Dodaj novu kategoriju</a>
    </p>
    <p>
        <a href="/Artikal/Index">Listing artikala</a>
    </p>
    <table class="table">
        <tr>
            <th>
                Identifikacioni broj kategorije
            </th>
            <th>
                Naziv kategorije
            </th>
            <th>
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.KategorijaId
                </td>
                <td>
                    @item.NazivKategorije
                </td>
                <td>
                    <a href="/KategorijaOdece/Brisi/@item.KategorijaId ">Brisi</a>
                </td>
                <td>
                    <a href="/KategorijaOdece/Izmeni/@item.KategorijaId">Izmeni</a>
                </td>
            </tr>
        }

    </table>

Modul2TestMiljanVasovic/Views/KategorijaOdece/Izmeni.cshtml
@model Modul2TestMiljanVasovic.Models.ViewModels.ArtikalKategorijaViewModel

@{
    ViewBag.Title = "Izmeni";
}

<h2>Izmeni</h2>


@using (Html.BeginForm("Izmeni", "KategorijaOdece", FormMethod.Post))
{
    <form method="post">
        <div class="form-group">
            @Html.HiddenFor(n => n.KategorijaOdeceModel.KategorijaId)

        </div>
        <div class="form-group">
            @Html.LabelFor(n => n.KategorijaOdeceModel.NazivKategorije)
            @Html.TextBoxFor(n => n.KategorijaOdeceModel.NazivKategorije)
            @Html.ValidationMessageFor(n => n.KategorijaOdeceModel.NazivKategorije)
        </div>
        <div class="form-group">
            <input class="btn-default" type="submit" />
        </div>
    </form>


}